name: Dev tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
permissions:
  checks: write
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn "-Dorientdb.test.env=ci" --batch-mode package --file pom.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests report for ${{ matrix.os }} - ${{ matrix.java-version }} 
          path: ${{ github.workspace }}/**/surefire-reports/*
          reporter: java-junit  
      - name: Uplodad tests artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: Tests files for ${{ matrix.os }} - ${{ matrix.java-version }} suite
          path: ${{ github.workspace }}/**/surefire-reports/*
