name: Dev tests
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]
permissions:
  checks: write
  contents: read
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        java-version: ['17', '21']
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with Maven
        run: mvn "-Dorientdb.test.env=ci" -B package --file pom.xml    
      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit tests on  ${{ runner.os }}-${{ matrix.java-version }}
          path: ${{ github.workspace }}/target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
